apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: demo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: demo-service:v1
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/transaction_db"
            - name: MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT
              value: "http://tempo:4318/v1/traces"
            - name: SPLUNK_HEC_URL
              value: "http://10.42.0.1:8088"
            - name: SPLUNK_HEC_TOKEN
              value: "6c2439e8-874f-474c-8397-f924548296b2"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
